läuft!!!

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,11 +1,12 @@
+
 services:
     quartz:
-        name: quartz
         image: fshrmnsfrnd/quartz
         ports:
-            - <port>:8080
+            - "8080:8080"
         volumes:
-            - <your_local_path_to_md_files>:/usr/src/app/content/
+            - ./content/:/usr/src/app/content/:ro
+            - quartz_public:/usr/src/app/public/:rw
         environment:
             - PAGE_TITLE=Quartz 4
             - PAGE_TITLE_SUFFIX=
@@ -34,3 +35,28 @@ services:
             - DARK_MODE_SECONDARY=#7b97aa
             - DARK_MODE_TERTIARY=#84a59d
             - DARK_MODE_TEXT_HIGHLIGHT=#b3aa0288
+        restart: always
+        command: >
+            sh -c "
+              while true; do
+                echo \"[builder] start $(date)\";
+                cd /usr/src/app/;
+                npx quartz build --output ./public/quartz && echo \"build success\" || echo \"build failed\";
+                cp -r /usr/src/app/public/quartz/* /usr/src/app/public/nginx/  && echo \"copy success\"|| echo \"copy failed\";
+                sleep 3600;
+              done
+            "
+
+    nginx:
+        image: nginx:latest
+        ports:
+            - "80:80"
+        volumes:
+            - ./nginx.conf:/etc/nginx/nginx.conf:ro
+            - quartz_public:/usr/share/nginx/html:ro
+        depends_on:
+            - quartz
+
+volumes:
+    quartz_public:
+        
