added \

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -35,19 +35,20 @@ services:
             - DARK_MODE_TEXT_HIGHLIGHT=#b3aa0288
         command: >
             sh -c "
-              while true; do
-                echo \"[builder] start $(date)\";
-                cd /usr/src/app/;
-                npx quartz build --output ./public/quartz && build_status="success" || build_status="failed";
-                
-                if build_status="success"; then
-                  cp -r /usr/src/app/public/quartz/* /usr/src/app/public/nginx/  && echo "copy success"|| echo "copy failed";
-                else
-                  echo "build failed";
-                fi
-                
-                sleep 3600;
-              done
+                while true; do
+                    echo \"[builder] start $(date)\";
+                    cd /usr/src/app/;
+                    npx quartz build --output ./public/quartz && build_status=\"success\" || build_status=\"failed\";
+                    
+                    if build_status=\"success\"; then
+                        cp -r /usr/src/app/public/quartz/* /usr/src/app/public/nginx/  && echo \"copy success\"|| echo \"copy failed\";
+                    else
+                        echo \"build failed\";
+                        echo \"copy aborted\";
+                    fi
+                    
+                    sleep 3600;
+                done
             "
         restart: always
 
