copy to nginx only when build success

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -38,8 +38,14 @@ services:
               while true; do
                 echo \"[builder] start $(date)\";
                 cd /usr/src/app/;
-                npx quartz build --output ./public/quartz && echo \"build success\" || echo \"build failed\";
-                cp -r /usr/src/app/public/quartz/* /usr/src/app/public/nginx/  && echo \"copy success\"|| echo \"copy failed\";
+                npx quartz build --output ./public/quartz && build_status="success" || build_status="failed";
+                
+                if build_status="success"; then
+                  cp -r /usr/src/app/public/quartz/* /usr/src/app/public/nginx/  && echo "copy success"|| echo "copy failed";
+                else
+                  echo "build failed";
+                fi
+                
                 sleep 3600;
               done
             "
